version: '3.7'
services:
  app:
    build:
      context: app
      args:
        - GOOGLE_API_KEY
        - PORT=8080
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on: 
      - db
    environment:
      - MYSQL_ADDRESS=db
      - MYSQL_DATABASE=order-app
      - MYSQL_USER=order-admin
      - MYSQL_PASSWORD=9X2mhC7CUrCtjJXH
  tester:
    build:
      context: app
      args:
        - GOOGLE_API_KEY
      target: tester
    depends_on: 
      - test-db
    environment:
    - MYSQL_ADDRESS=test-db
    - MYSQL_DATABASE=order-app
    - MYSQL_USER=order-admin
    - MYSQL_PASSWORD=9X2mhC7CUrCtjJXH
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=order-app
      - MYSQL_USER=order-admin
      - MYSQL_PASSWORD=9X2mhC7CUrCtjJXH
    volumes:
      - api-db:/var/lib/mysql
  test-db:
    image: mysql:5.7
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=order-app
      - MYSQL_USER=order-admin
      - MYSQL_PASSWORD=9X2mhC7CUrCtjJXH
volumes:
  api-db: